version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/logs:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  loan-app-db:
    image: mysql:8
    container_name: loan-app-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: loan-application-system-db
    ports:
      - 3306:3306
    networks:
      - loan-application-system-mysql

  loan-application-system-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: loan-application-system
    container_name: loan-application-system-container
    restart: always
    ports:
      - 8080:8080
    networks:
      - loan-application-system-mysql
    depends_on:
      - loan-app-db

networks:
  loan-application-system-mysql:
    driver: bridge