version: '3'

services:

  loan-app-db:
    image: mysql:8.0.17
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: loan-app
    ports:
      - "3306:3306"
 